openapi: 3.1.0
info:
  contact:
    email: support@konghq.com
    name: Kong Inc
    url: https://konghq.com
  description: 'OpenAPI 3.0 spec for Kong Gateway''s Admin API.


    You can learn more about Kong Gateway at [developer.konghq.com](https://developer.konghq.com).

    Give Kong a star at the [Kong/kong](https://github.com/kong/kong) repository.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Kong Enterprise Admin ACLs Portal Team Roles API
  version: 3.14.0
servers:
- description: Default Admin API URL
  url: '{protocol}://{hostname}:{port}{path}'
  variables:
    hostname:
      default: localhost
      description: Hostname for Kong's Admin API
    path:
      default: /
      description: Base path for Kong's Admin API
    port:
      default: '8001'
      description: Port for Kong's Admin API
    protocol:
      default: http
      description: Protocol for requests to Kong's Admin API
      enum:
      - http
      - https
security:
- adminToken: []
tags:
- name: Portal Team Roles
  description: APIs related to Konnect Developer Portal developer team roles.
paths:
  /v3/portal-roles:
    get:
      operationId: list-portal-roles
      summary: List Portal Roles
      description: List roles that can be assigned to teams in a portal. Each role provides a set of permissions to perform an action on a resource.
      responses:
        '200':
          $ref: '#/components/responses/ListRoles'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
      - Portal Team Roles
  /v3/portals/{portalId}/teams/{teamId}/assigned-roles:
    parameters:
    - $ref: '#/components/parameters/PortalId'
    - $ref: '#/components/parameters/TeamId'
    - $ref: '#/components/parameters/PageSize'
    - $ref: '#/components/parameters/PageNumber'
    get:
      operationId: list-portal-team-roles
      summary: List Team Roles
      description: Lists the roles belonging to a developer team. Each role provides permissions to perform actions on a specified resource or collection.
      responses:
        '200':
          $ref: '#/components/responses/AssignedPortalRoleCollection'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
      - Portal Team Roles
    post:
      operationId: assign-role-to-portal-teams
      summary: Assign Role
      description: Assign a role to a developer team. This associates the set of permissions in a role with the team, so that they will be applied to any developer who is a member of the team.
      requestBody:
        $ref: '#/components/requestBodies/PortalAssignRole'
      responses:
        '201':
          $ref: '#/components/responses/PortalAssignedRole'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
      tags:
      - Portal Team Roles
  /v3/portals/{portalId}/teams/{teamId}/assigned-roles/{roleId}:
    parameters:
    - $ref: '#/components/parameters/RoleId'
    - $ref: '#/components/parameters/PortalId'
    - $ref: '#/components/parameters/TeamId'
    delete:
      operationId: remove-role-from-portal-team
      summary: Remove Role
      description: Removes an assigned role from a developer team. This deletes the association of the role with team and each of its members.
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
      - Portal Team Roles
components:
  schemas:
    InvalidParameterMinimumLength:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
          - min_length
          - min_digits
          - min_lowercase
          - min_uppercase
          - min_symbols
          - min_items
          - min
          nullable: false
          readOnly: true
          x-speakeasy-unknown-values: allow
        minimum:
          type: integer
          example: 8
        source:
          type: string
          example: body
        reason:
          type: string
          example: must have at least 8 characters
          readOnly: true
      additionalProperties: false
      required:
      - field
      - reason
      - rule
      - minimum
    AssignedPortalRoleCollectionResponse:
      description: A paginated list of roles assigned to a team.
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/PaginatedMeta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/PortalAssignedRoleResponse'
      example:
        meta:
          page:
            number: 1
            size: 10
            total: 3
        data:
        - id: b02e23c5-8ee4-4e5a-99f4-43329923adce
          role_name: API Viewer
          entity_id: 437c7192-fea0-4f35-8478-c8d57783f8c1
          entity_type_name: Services
          entity_region: us
        - id: b02e23c5-8ee4-4e5a-99f4-43329923adce
          role_name: API Consumer
          entity_id: 437c7192-fea0-4f35-8478-c8d57783f8c1
          entity_type_name: Services
          entity_region: us
        - id: 869d9402-f117-4f9a-840f-69acaf70a81a
          role_name: API Viewer
          entity_id: 18ee2573-dec0-4b83-be99-fa7700bcdc61
          entity_type_name: Services
          entity_region: us
      required:
      - meta
      - data
      title: AssignedPortalRoleCollectionResponse
    ListRolesResponse:
      description: The set of roles available to associate with resources and assign to teams.
      type: object
      properties:
        services:
          type: object
          properties:
            name:
              type: string
              enum:
              - Services
            roles:
              type: object
              properties:
                apiviewer:
                  type: object
                  properties:
                    name:
                      type: string
                      enum:
                      - API Viewer
                    description:
                      type: string
                      enum:
                      - API Viewers have read-only access to the documentation of a service in a portal
                  required:
                  - name
                  - description
                apiconsumer:
                  type: object
                  properties:
                    name:
                      type: string
                      enum:
                      - API Consumer
                    description:
                      type: string
                      enum:
                      - API Consumers can make calls to the given service
                  required:
                  - name
                  - description
              required:
              - apiviewer
              - apiconsumer
          required:
          - name
          - roles
      example:
        services:
          name: Services
          roles:
            apiviewer:
              name: API Viewer
              description: API Viewers have read-only access to the documentation of a service in a portal
            apiconsumer:
              name: API Consumer
              description: API Consumers can make calls to the given service
      required:
      - services
      title: ListRolesResponse
    ConflictError:
      allOf:
      - $ref: '#/components/schemas/BaseError'
      - type: object
        properties:
          status:
            example: 409
          title:
            example: Conflict
          type:
            example: https://httpstatuses.com/409
          instance:
            example: kong:trace:1234567890
          detail:
            example: Conflict
    InvalidParameterChoiceItem:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
          - enum
          nullable: false
          readOnly: true
        reason:
          type: string
          example: is a required field
          readOnly: true
        choices:
          type: array
          items: {}
          minItems: 1
          nullable: false
          readOnly: true
          uniqueItems: true
        source:
          type: string
          example: body
      additionalProperties: false
      required:
      - field
      - reason
      - rule
      - choices
    InvalidParameterMaximumLength:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
          - max_length
          - max_items
          - max
          nullable: false
          readOnly: true
          x-speakeasy-unknown-values: allow
        maximum:
          type: integer
          example: 8
        source:
          type: string
          example: body
        reason:
          type: string
          example: must not have more than 8 characters
          readOnly: true
      additionalProperties: false
      required:
      - field
      - reason
      - rule
      - maximum
    ForbiddenError:
      allOf:
      - $ref: '#/components/schemas/BaseError'
      - type: object
        properties:
          status:
            example: 403
          title:
            example: Forbidden
          type:
            example: https://httpstatuses.com/403
          instance:
            example: kong:trace:1234567890
          detail:
            example: Forbidden
    UnauthorizedError:
      allOf:
      - $ref: '#/components/schemas/BaseError'
      - type: object
        properties:
          status:
            example: 401
          title:
            example: Unauthorized
          type:
            example: https://httpstatuses.com/401
          instance:
            example: kong:trace:1234567890
          detail:
            example: Invalid credentials
    PaginatedMeta:
      description: returns the pagination information
      type: object
      properties:
        page:
          $ref: '#/components/schemas/PageMeta'
      required:
      - page
      title: PaginatedMeta
      x-speakeasy-terraform-ignore: true
    BaseError:
      description: standard error
      type: object
      properties:
        status:
          description: 'The HTTP status code of the error. Useful when passing the response

            body to child properties in a frontend UI. Must be returned as an integer.

            '
          type: integer
          readOnly: true
        title:
          description: 'A short, human-readable summary of the problem. It should not

            change between occurences of a problem, except for localization.

            Should be provided as "Sentence case" for direct use in the UI.

            '
          type: string
          readOnly: true
        type:
          description: The error type.
          type: string
          readOnly: true
        instance:
          description: 'Used to return the correlation ID back to the user, in the format

            kong:trace:<correlation_id>. This helps us find the relevant logs

            when a customer reports an issue.

            '
          type: string
          readOnly: true
        detail:
          description: 'A human readable explanation specific to this occurence of the problem.

            This field may contain request/entity data to help the user understand

            what went wrong. Enclose variable values in square brackets. Should be

            provided as "Sentence case" for direct use in the UI.

            '
          type: string
          readOnly: true
      required:
      - status
      - title
      - instance
      - detail
      title: Error
    InvalidParameterDependentItem:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
          - dependent_fields
          nullable: true
          readOnly: true
        reason:
          type: string
          example: is a required field
          readOnly: true
        dependents:
          type: array
          items: {}
          nullable: true
          readOnly: true
          uniqueItems: true
        source:
          type: string
          example: body
      additionalProperties: false
      required:
      - field
      - rule
      - reason
      - dependents
    PortalAssignRoleRequest:
      description: An assigned role associates a service and an action to a team.
      type: object
      properties:
        role_name:
          type: string
          example: API Viewer
        entity_id:
          type: string
          format: uuid
          example: e67490ce-44dc-4cbd-b65e-b52c746fc26a
        entity_type_name:
          type: string
          example: Services
        entity_region:
          description: Region of the entity.
          type: string
          example: eu
          enum:
          - us
          - eu
          - au
          - me
          - in
          - sg
          - '*'
          x-speakeasy-unknown-values: allow
      example:
        role_name: API Viewer
        entity_id: 18ee2573-dec0-4b83-be99-fa7700bcdc61
        entity_type_name: Services
        entity_region: us
      required:
      - role_name
      - entity_id
      - entity_type_name
      - entity_region
      title: PortalAssignRoleRequest
    InvalidRules:
      description: invalid parameters rules
      type: string
      enum:
      - required
      - is_array
      - is_base64
      - is_boolean
      - is_date_time
      - is_integer
      - is_null
      - is_number
      - is_object
      - is_string
      - is_uuid
      - is_fqdn
      - is_arn
      - unknown_property
      - missing_reference
      - is_label
      - matches_regex
      - invalid
      - is_supported_network_availability_zone_list
      - is_supported_network_cidr_block
      - is_supported_provider_region
      - type
      nullable: true
      readOnly: true
      x-speakeasy-unknown-values: allow
    InvalidParameters:
      description: invalid parameters
      type: array
      items:
        oneOf:
        - $ref: '#/components/schemas/InvalidParameterStandard'
        - $ref: '#/components/schemas/InvalidParameterMinimumLength'
        - $ref: '#/components/schemas/InvalidParameterMaximumLength'
        - $ref: '#/components/schemas/InvalidParameterChoiceItem'
        - $ref: '#/components/schemas/InvalidParameterDependentItem'
      minItems: 1
      nullable: false
      uniqueItems: true
    BadRequestError:
      allOf:
      - $ref: '#/components/schemas/BaseError'
      - type: object
        required:
        - invalid_parameters
        properties:
          invalid_parameters:
            $ref: '#/components/schemas/InvalidParameters'
    InvalidParameterStandard:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          $ref: '#/components/schemas/InvalidRules'
        source:
          type: string
          example: body
        reason:
          type: string
          example: is a required field
          readOnly: true
      additionalProperties: false
      required:
      - field
      - reason
    PortalAssignedRoleResponse:
      description: An assigned role associates a service and an action to a team.
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: eaf7adf1-32c8-4bbf-b960-d1f8456afe67
        role_name:
          type: string
          example: API Viewer
        entity_id:
          type: string
          format: uuid
          example: 817d0422-45c9-4d88-8d64-45aef05c1ae7
        entity_type_name:
          type: string
          example: Services
        entity_region:
          description: Region of the entity.
          type: string
          example: eu
          enum:
          - us
          - eu
          - au
          - me
          - in
          - sg
          - '*'
          x-speakeasy-unknown-values: allow
      example:
        id: 1a3c2169-27f8-4594-926b-41df3432d5dc
        role_name: API Viewer
        entity_id: 18ee2573-dec0-4b83-be99-fa7700bcdc61
        entity_type_name: Services
        entity_region: us
      required:
      - id
      - role_name
      - entity_id
      - entity_type_name
      - entity_region
      title: PortalAssignedRoleResponse
    PageMeta:
      description: Contains pagination query parameters and the total number of objects returned.
      type: object
      properties:
        number:
          type: number
          example: 1
          x-speakeasy-terraform-ignore: true
        size:
          type: number
          example: 10
          x-speakeasy-terraform-ignore: true
        total:
          type: number
          example: 100
          x-speakeasy-terraform-ignore: true
      required:
      - number
      - size
      - total
    NotFoundError:
      allOf:
      - $ref: '#/components/schemas/BaseError'
      - type: object
        properties:
          status:
            example: 404
          title:
            example: Not Found
          type:
            example: https://httpstatuses.com/404
          instance:
            example: kong:trace:1234567890
          detail:
            example: Not found
  responses:
    NotFound:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
    Conflict:
      description: Conflict
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ConflictError'
    AssignedPortalRoleCollection:
      description: A paginated collection of assigned roles.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AssignedPortalRoleCollectionResponse'
    PortalAssignedRole:
      description: Details about the role assignment.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PortalAssignedRoleResponse'
    Unauthorized:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            description: The error response object.
            type: object
            properties:
              status:
                description: The HTTP status code.
                type: integer
                example: 403
              title:
                description: The Error Response.
                type: string
                example: Unauthorized
              instance:
                description: The Konnect traceback code.
                type: string
                example: konnect:trace:952172606039454040
              detail:
                description: Details about the error response.
                type: string
                example: You do not have permission to perform this action
            $ref: '#/components/schemas/UnauthorizedError'
            title: Unauthorized Response
    ListRoles:
      description: A set of roles available in portals.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListRolesResponse'
    Forbidden:
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ForbiddenError'
  parameters:
    TeamId:
      x-speakeasy-match: id
      schema:
        type: string
        format: uuid
        example: d32d905a-ed33-46a3-a093-d8f536af9a8a
      name: teamId
      in: path
      required: true
      description: ID of the team.
    RoleId:
      schema:
        type: string
        format: uuid
        example: 8350205f-a305-4e39-abe9-bc082a80091a
      name: roleId
      in: path
      required: true
    PageSize:
      name: page[size]
      description: The maximum number of items to include per page. The last page of a collection may include fewer items.
      required: false
      in: query
      allowEmptyValue: true
      schema:
        type: integer
        example: 10
      x-speakeasy-terraform-ignore: true
    PageNumber:
      name: page[number]
      description: Determines which page of the entities to retrieve.
      required: false
      in: query
      allowEmptyValue: true
      schema:
        type: integer
        example: 1
      x-speakeasy-terraform-ignore: true
    PortalId:
      schema:
        type: string
        format: uuid
        example: f32d905a-ed33-46a3-a093-d8f536af9a8a
      name: portalId
      in: path
      required: true
      description: ID of the portal.
  requestBodies:
    PortalAssignRole:
      description: Assign a role to a team.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PortalAssignRoleRequest'
  securitySchemes:
    adminToken:
      in: header
      name: Kong-Admin-Token
      type: apiKey
externalDocs:
  description: Documentation for Kong Gateway and its APIs
  url: https://developer.konghq.com
