openapi: 3.1.0
info:
  contact:
    email: support@konghq.com
    name: Kong Inc
    url: https://konghq.com
  description: 'OpenAPI 3.0 spec for Kong Gateway''s Admin API.


    You can learn more about Kong Gateway at [developer.konghq.com](https://developer.konghq.com).

    Give Kong a star at the [Kong/kong](https://github.com/kong/kong) repository.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Kong Enterprise Admin ACLs API-keys API
  version: 3.14.0
servers:
- description: Default Admin API URL
  url: '{protocol}://{hostname}:{port}{path}'
  variables:
    hostname:
      default: localhost
      description: Hostname for Kong's Admin API
    path:
      default: /
      description: Base path for Kong's Admin API
    port:
      default: '8001'
      description: Port for Kong's Admin API
    protocol:
      default: http
      description: Protocol for requests to Kong's Admin API
      enum:
      - http
      - https
security:
- adminToken: []
tags:
- name: API-keys
paths:
  /{workspace}/consumers/{ConsumerIdForNestedEntities}/key-auth:
    post:
      x-speakeasy-entity-operation:
        terraform-datasource: null
        terraform-resource: KeyAuth#create
      operationId: create-key-auth-with-consumer
      summary: Create a new API-key associated with a Consumer
      description: Create a new API-key associated with a Consumer
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities'
      - $ref: '#/components/parameters/Workspace'
      requestBody:
        description: Description of new API-key for creation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KeyAuthWithoutParents'
      responses:
        '201':
          description: Successfully created API-key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyAuth'
      tags:
      - API-keys
  /{workspace}/consumers/{ConsumerIdForNestedEntities}/key-auth/{KeyAuthId}:
    delete:
      x-speakeasy-entity-operation:
        terraform-datasource: null
        terraform-resource: KeyAuth#delete
      operationId: delete-key-auth-with-consumer
      summary: Delete a an API-key associated with a Consumer
      description: Delete a an API-key associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities'
      - $ref: '#/components/parameters/KeyAuthId'
      - $ref: '#/components/parameters/Workspace'
      responses:
        '204':
          description: Successfully deleted API-key or the resource didn't exist
      tags:
      - API-keys
    get:
      x-speakeasy-entity-operation:
        terraform-datasource: null
        terraform-resource: KeyAuth#read
      operationId: get-key-auth-with-consumer
      summary: Get an API-key associated with a Consumer
      description: Get an API-key associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities'
      - $ref: '#/components/parameters/KeyAuthId'
      - $ref: '#/components/parameters/Workspace'
      responses:
        '200':
          description: Successfully fetched API-key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyAuth'
        '404':
          description: Resource does not exist
      tags:
      - API-keys
  /v2/control-planes/{controlPlaneId}/core-entities/consumers/{ConsumerIdForNestedEntities}/key-auth:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: list-key-auth-with-consumer
      summary: List all API-keys associated with a Consumer
      description: List all API-keys associated with a Consumer
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      - $ref: '#/components/parameters/PaginationSize'
      - $ref: '#/components/parameters/PaginationOffset'
      - $ref: '#/components/parameters/PaginationTagsFilter'
      responses:
        '200':
          description: A successful response listing API-keys
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/KeyAuth_2'
                  next:
                    $ref: '#/components/schemas/PaginationNextResponse'
                  offset:
                    $ref: '#/components/schemas/PaginationOffsetResponse'
      tags:
      - API-keys
    post:
      operationId: create-key-auth-with-consumer
      summary: Create a new API-key associated with a Consumer
      description: Create a new API-key associated with a Consumer
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      requestBody:
        description: Description of new API-key for creation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KeyAuthWithoutParents_2'
      responses:
        '201':
          description: Successfully created API-key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyAuth_2'
      tags:
      - API-keys
  /v2/control-planes/{controlPlaneId}/core-entities/consumers/{ConsumerIdForNestedEntities}/key-auth/{KeyAuthId}:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    delete:
      operationId: delete-key-auth-with-consumer
      summary: Delete a an API-key associated with a Consumer
      description: Delete a an API-key associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      - $ref: '#/components/parameters/KeyAuthId_2'
      responses:
        '204':
          description: Successfully deleted API-key or the resource didn't exist
      tags:
      - API-keys
    get:
      operationId: get-key-auth-with-consumer
      summary: Get an API-key associated with a Consumer
      description: Get an API-key associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      - $ref: '#/components/parameters/KeyAuthId_2'
      responses:
        '200':
          description: Successfully fetched API-key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyAuth_2'
        '404':
          description: Resource does not exist
      tags:
      - API-keys
    put:
      operationId: upsert-key-auth-with-consumer
      summary: Upsert an API-key associated with a Consumer
      description: Create or Update an API-key associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      - $ref: '#/components/parameters/KeyAuthId_2'
      requestBody:
        description: Description of the API-key
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KeyAuthWithoutParents_2'
      responses:
        '200':
          description: Successfully upserted API-key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyAuth_2'
      tags:
      - API-keys
  /v2/control-planes/{controlPlaneId}/core-entities/key-auths:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: list-key-auth
      summary: List all API-keys
      description: List all API-keys
      parameters:
      - $ref: '#/components/parameters/PaginationSize'
      - $ref: '#/components/parameters/PaginationOffset'
      - $ref: '#/components/parameters/PaginationTagsFilter'
      responses:
        '200':
          description: A successful response listing API-keys
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/KeyAuth_2'
                  next:
                    $ref: '#/components/schemas/PaginationNextResponse'
                  offset:
                    $ref: '#/components/schemas/PaginationOffsetResponse'
        '401':
          $ref: '#/components/responses/HTTP401Error'
      tags:
      - API-keys
  /v2/control-planes/{controlPlaneId}/core-entities/key-auths/{KeyAuthId}:
    parameters:
    - $ref: '#/components/parameters/KeyAuthId_2'
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: get-key-auth
      summary: Get an API-key
      description: Get an API-key using ID.
      responses:
        '200':
          description: Successfully fetched API-key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyAuth_2'
        '401':
          $ref: '#/components/responses/HTTP401Error'
        '404':
          description: Resource does not exist
      tags:
      - API-keys
components:
  parameters:
    KeyAuthId_2:
      description: ID of the API-key to lookup
      example: ''
      in: path
      name: KeyAuthId
      required: true
      schema:
        type: string
    ConsumerIdForNestedEntities_2:
      description: Consumer ID for nested entities
      example: ''
      in: path
      name: ConsumerIdForNestedEntities
      required: true
      schema:
        type: string
    PaginationSize:
      description: Number of resources to be returned.
      in: query
      name: size
      schema:
        type: integer
        default: 100
        maximum: 1000
        minimum: 1
    KeyAuthId:
      description: ID of the API-key to lookup
      example: ''
      in: path
      name: KeyAuthId
      required: true
      schema:
        type: string
      x-speakeasy-match: id
    Workspace:
      description: The name of the workspace
      in: path
      name: workspace
      required: true
      schema:
        type: string
        example: team-payments
        default: default
    PaginationOffset:
      allowEmptyValue: true
      description: Offset from which to return the next set of resources. Use the value of the 'offset' field from the response of a list operation as input here to paginate through all the resources
      in: query
      name: offset
      schema:
        type: string
    PaginationTagsFilter:
      allowEmptyValue: true
      description: A list of tags to filter the list of resources on. Multiple tags can be concatenated using ',' to mean AND or using '/' to mean OR.
      example: tag1,tag2
      in: query
      name: tags
      schema:
        type: string
    ConsumerIdForNestedEntities:
      description: Consumer ID for nested entities
      example: ''
      in: path
      name: ConsumerIdForNestedEntities
      required: true
      schema:
        type: string
      x-speakeasy-name-override: consumer_id
    controlPlaneId:
      name: controlPlaneId
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: 9524ec7d-36d9-465d-a8c5-83a3c9390458
      description: The UUID of your control plane. This variable is available in the Konnect manager.
      x-speakeasy-param-force-new: true
  schemas:
    PaginationOffsetResponse:
      description: Offset is used to paginate through the API. Provide this value to the next list operation to fetch the next page
      type: string
    GatewayUnauthorizedError:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
      required:
      - message
      - status
    PaginationNextResponse:
      description: URI to the next page (may be null)
      type: string
    KeyAuthWithoutParents_2:
      type: object
      properties:
        consumer:
          type: object
          nullable: true
          properties:
            id:
              type: string
          x-foreign: true
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        key:
          type: string
          nullable: true
        tags:
          description: A set of strings representing tags.
          type: array
          items:
            description: A string representing a tag.
            type: string
          nullable: true
        ttl:
          description: key-auth ttl in seconds
          type: integer
          nullable: true
      example:
        id: b2f34145-0343-41a4-9602-4c69dec2f269
        key: IL1deIyHyQA40WpeLeA1bIUXuvTwlGjo
      additionalProperties: false
    KeyAuth_2:
      type: object
      properties:
        consumer:
          type: object
          nullable: true
          properties:
            id:
              type: string
          x-foreign: true
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        key:
          type: string
          nullable: true
        tags:
          description: A set of strings representing tags.
          type: array
          items:
            description: A string representing a tag.
            type: string
          nullable: true
        ttl:
          description: key-auth ttl in seconds
          type: integer
          nullable: true
      example:
        consumer:
          id: 84a73fb8-50fc-44a7-a4d5-aa17728ee83f
        id: b2f34145-0343-41a4-9602-4c69dec2f269
        key: IL1deIyHyQA40WpeLeA1bIUXuvTwlGjo
      additionalProperties: false
    KeyAuth:
      x-speakeasy-entity: KeyAuth
      type: object
      properties:
        consumer:
          type: object
          nullable: true
          properties:
            id:
              type: string
          x-foreign: true
          x-speakeasy-terraform-ignore: true
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        key:
          type: string
          nullable: true
        tags:
          description: A set of strings representing tags.
          type: array
          items:
            description: A string representing a tag.
            type: string
          nullable: true
        ttl:
          description: key-auth ttl in seconds
          type: integer
          nullable: true
      example:
        consumer:
          id: 84a73fb8-50fc-44a7-a4d5-aa17728ee83f
        id: b2f34145-0343-41a4-9602-4c69dec2f269
        key: IL1deIyHyQA40WpeLeA1bIUXuvTwlGjo
      additionalProperties: false
    KeyAuthWithoutParents:
      x-speakeasy-entity: KeyAuth
      type: object
      properties:
        consumer:
          type: object
          nullable: true
          properties:
            id:
              type: string
          x-foreign: true
          x-speakeasy-terraform-ignore: true
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        key:
          type: string
          nullable: true
        tags:
          description: A set of strings representing tags.
          type: array
          items:
            description: A string representing a tag.
            type: string
          nullable: true
        ttl:
          description: key-auth ttl in seconds
          type: integer
          nullable: true
      example:
        id: b2f34145-0343-41a4-9602-4c69dec2f269
        key: IL1deIyHyQA40WpeLeA1bIUXuvTwlGjo
      additionalProperties: false
  responses:
    HTTP401Error:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GatewayUnauthorizedError'
  securitySchemes:
    adminToken:
      in: header
      name: Kong-Admin-Token
      type: apiKey
externalDocs:
  description: Documentation for Kong Gateway and its APIs
  url: https://developer.konghq.com
