openapi: 3.1.0
info:
  contact:
    email: support@konghq.com
    name: Kong Inc
    url: https://konghq.com
  description: 'OpenAPI 3.0 spec for Kong Gateway''s Admin API.


    You can learn more about Kong Gateway at [developer.konghq.com](https://developer.konghq.com).

    Give Kong a star at the [Kong/kong](https://github.com/kong/kong) repository.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Kong Enterprise Admin ACLs HMAC-auth credentials API
  version: 3.14.0
servers:
- description: Default Admin API URL
  url: '{protocol}://{hostname}:{port}{path}'
  variables:
    hostname:
      default: localhost
      description: Hostname for Kong's Admin API
    path:
      default: /
      description: Base path for Kong's Admin API
    port:
      default: '8001'
      description: Port for Kong's Admin API
    protocol:
      default: http
      description: Protocol for requests to Kong's Admin API
      enum:
      - http
      - https
security:
- adminToken: []
tags:
- name: HMAC-auth credentials
paths:
  /{workspace}/consumers/{ConsumerIdForNestedEntities}/hmac-auth:
    post:
      x-speakeasy-entity-operation:
        terraform-datasource: null
        terraform-resource: HMACAuth#create
      operationId: create-hmac-auth-with-consumer
      summary: Create a new HMAC-auth credential associated with a Consumer
      description: Create a new HMAC-auth credential associated with a Consumer
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities'
      - $ref: '#/components/parameters/Workspace'
      requestBody:
        description: Description of new HMAC-auth credential for creation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HMACAuthWithoutParents'
      responses:
        '201':
          description: Successfully created HMAC-auth credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HMACAuth'
      tags:
      - HMAC-auth credentials
  /{workspace}/consumers/{ConsumerIdForNestedEntities}/hmac-auth/{HMACAuthId}:
    delete:
      x-speakeasy-entity-operation:
        terraform-datasource: null
        terraform-resource: HMACAuth#delete
      operationId: delete-hmac-auth-with-consumer
      summary: Delete a a HMAC-auth credential associated with a Consumer
      description: Delete a a HMAC-auth credential associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities'
      - $ref: '#/components/parameters/HMACAuthId'
      - $ref: '#/components/parameters/Workspace'
      responses:
        '204':
          description: Successfully deleted HMAC-auth credential or the resource didn't exist
      tags:
      - HMAC-auth credentials
    get:
      x-speakeasy-entity-operation:
        terraform-datasource: null
        terraform-resource: HMACAuth#read
      operationId: get-hmac-auth-with-consumer
      summary: Get a HMAC-auth credential associated with a Consumer
      description: Get a HMAC-auth credential associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities'
      - $ref: '#/components/parameters/HMACAuthId'
      - $ref: '#/components/parameters/Workspace'
      responses:
        '200':
          description: Successfully fetched HMAC-auth credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HMACAuth'
        '404':
          description: Resource does not exist
      tags:
      - HMAC-auth credentials
  /v2/control-planes/{controlPlaneId}/core-entities/consumers/{ConsumerIdForNestedEntities}/hmac-auth:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: list-hmac-auth-with-consumer
      summary: List all HMAC-auth credentials associated with a Consumer
      description: List all HMAC-auth credentials associated with a Consumer
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      - $ref: '#/components/parameters/PaginationSize'
      - $ref: '#/components/parameters/PaginationOffset'
      - $ref: '#/components/parameters/PaginationTagsFilter'
      responses:
        '200':
          description: A successful response listing HMAC-auth credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/HMACAuth_2'
                  next:
                    $ref: '#/components/schemas/PaginationNextResponse'
                  offset:
                    $ref: '#/components/schemas/PaginationOffsetResponse'
      tags:
      - HMAC-auth credentials
    post:
      operationId: create-hmac-auth-with-consumer
      summary: Create a new HMAC-auth credential associated with a Consumer
      description: Create a new HMAC-auth credential associated with a Consumer
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      requestBody:
        description: Description of new HMAC-auth credential for creation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HMACAuthWithoutParents_2'
      responses:
        '201':
          description: Successfully created HMAC-auth credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HMACAuth_2'
      tags:
      - HMAC-auth credentials
  /v2/control-planes/{controlPlaneId}/core-entities/consumers/{ConsumerIdForNestedEntities}/hmac-auth/{HMACAuthId}:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    delete:
      operationId: delete-hmac-auth-with-consumer
      summary: Delete a a HMAC-auth credential associated with a Consumer
      description: Delete a a HMAC-auth credential associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      - $ref: '#/components/parameters/HMACAuthId_2'
      responses:
        '204':
          description: Successfully deleted HMAC-auth credential or the resource didn't exist
      tags:
      - HMAC-auth credentials
    get:
      operationId: get-hmac-auth-with-consumer
      summary: Get a HMAC-auth credential associated with a Consumer
      description: Get a HMAC-auth credential associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      - $ref: '#/components/parameters/HMACAuthId_2'
      responses:
        '200':
          description: Successfully fetched HMAC-auth credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HMACAuth_2'
        '404':
          description: Resource does not exist
      tags:
      - HMAC-auth credentials
    put:
      operationId: upsert-hmac-auth-with-consumer
      summary: Upsert a HMAC-auth credential associated with a Consumer
      description: Create or Update a HMAC-auth credential associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      - $ref: '#/components/parameters/HMACAuthId_2'
      requestBody:
        description: Description of the HMAC-auth credential
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HMACAuthWithoutParents_2'
      responses:
        '200':
          description: Successfully upserted HMAC-auth credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HMACAuth_2'
      tags:
      - HMAC-auth credentials
  /v2/control-planes/{controlPlaneId}/core-entities/hmac-auths:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: list-hmac-auth
      summary: List all HMAC-auth credentials
      description: List all HMAC-auth credentials
      parameters:
      - $ref: '#/components/parameters/PaginationSize'
      - $ref: '#/components/parameters/PaginationOffset'
      - $ref: '#/components/parameters/PaginationTagsFilter'
      responses:
        '200':
          description: A successful response listing HMAC-auth credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/HMACAuth_2'
                  next:
                    $ref: '#/components/schemas/PaginationNextResponse'
                  offset:
                    $ref: '#/components/schemas/PaginationOffsetResponse'
        '401':
          $ref: '#/components/responses/HTTP401Error'
      tags:
      - HMAC-auth credentials
  /v2/control-planes/{controlPlaneId}/core-entities/hmac-auths/{HMACAuthId}:
    parameters:
    - $ref: '#/components/parameters/HMACAuthId_2'
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: get-hmac-auth
      summary: Get a HMAC-auth credential
      description: Get a HMAC-auth credential using ID.
      responses:
        '200':
          description: Successfully fetched HMAC-auth credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HMACAuth_2'
        '401':
          $ref: '#/components/responses/HTTP401Error'
        '404':
          description: Resource does not exist
      tags:
      - HMAC-auth credentials
components:
  schemas:
    HMACAuth_2:
      type: object
      properties:
        consumer:
          type: object
          nullable: true
          properties:
            id:
              type: string
          x-foreign: true
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        secret:
          type: string
          nullable: true
          x-encrypted: true
        tags:
          description: A set of strings representing tags.
          type: array
          items:
            description: A string representing a tag.
            type: string
          nullable: true
        username:
          type: string
      example:
        consumer:
          id: 84a73fb8-50fc-44a7-a4d5-aa17728ee83f
        id: 75695322-e8a0-4109-aed4-5416b0308d85
        secret: wQazJ304DW5huJklHgUfjfiSyCyTAEDZ
        username: xerxes
      additionalProperties: false
      required:
      - username
    PaginationOffsetResponse:
      description: Offset is used to paginate through the API. Provide this value to the next list operation to fetch the next page
      type: string
    GatewayUnauthorizedError:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
      required:
      - message
      - status
    HMACAuth:
      x-speakeasy-entity: HMACAuth
      type: object
      properties:
        consumer:
          type: object
          nullable: true
          properties:
            id:
              type: string
          x-foreign: true
          x-speakeasy-terraform-ignore: true
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        secret:
          type: string
          nullable: true
          x-encrypted: true
        tags:
          description: A set of strings representing tags.
          type: array
          items:
            description: A string representing a tag.
            type: string
          nullable: true
        username:
          type: string
      example:
        consumer:
          id: 84a73fb8-50fc-44a7-a4d5-aa17728ee83f
        id: 75695322-e8a0-4109-aed4-5416b0308d85
        secret: wQazJ304DW5huJklHgUfjfiSyCyTAEDZ
        username: xerxes
      additionalProperties: false
      required:
      - username
    HMACAuthWithoutParents:
      x-speakeasy-entity: HMACAuth
      type: object
      properties:
        consumer:
          type: object
          nullable: true
          properties:
            id:
              type: string
          x-foreign: true
          x-speakeasy-terraform-ignore: true
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        secret:
          type: string
          nullable: true
          x-encrypted: true
        tags:
          description: A set of strings representing tags.
          type: array
          items:
            description: A string representing a tag.
            type: string
          nullable: true
        username:
          type: string
      example:
        id: 75695322-e8a0-4109-aed4-5416b0308d85
        secret: wQazJ304DW5huJklHgUfjfiSyCyTAEDZ
        username: xerxes
      additionalProperties: false
      required:
      - username
    HMACAuthWithoutParents_2:
      type: object
      properties:
        consumer:
          type: object
          nullable: true
          properties:
            id:
              type: string
          x-foreign: true
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        secret:
          type: string
          nullable: true
          x-encrypted: true
        tags:
          description: A set of strings representing tags.
          type: array
          items:
            description: A string representing a tag.
            type: string
          nullable: true
        username:
          type: string
      example:
        id: 75695322-e8a0-4109-aed4-5416b0308d85
        secret: wQazJ304DW5huJklHgUfjfiSyCyTAEDZ
        username: xerxes
      additionalProperties: false
      required:
      - username
    PaginationNextResponse:
      description: URI to the next page (may be null)
      type: string
  parameters:
    ConsumerIdForNestedEntities_2:
      description: Consumer ID for nested entities
      example: ''
      in: path
      name: ConsumerIdForNestedEntities
      required: true
      schema:
        type: string
    controlPlaneId:
      name: controlPlaneId
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: 9524ec7d-36d9-465d-a8c5-83a3c9390458
      description: The UUID of your control plane. This variable is available in the Konnect manager.
      x-speakeasy-param-force-new: true
    PaginationSize:
      description: Number of resources to be returned.
      in: query
      name: size
      schema:
        type: integer
        default: 100
        maximum: 1000
        minimum: 1
    Workspace:
      description: The name of the workspace
      in: path
      name: workspace
      required: true
      schema:
        type: string
        example: team-payments
        default: default
    PaginationOffset:
      allowEmptyValue: true
      description: Offset from which to return the next set of resources. Use the value of the 'offset' field from the response of a list operation as input here to paginate through all the resources
      in: query
      name: offset
      schema:
        type: string
    HMACAuthId_2:
      description: ID of the HMAC-auth credential to lookup
      example: 70e7b00b-72f2-471b-a5ce-9c4171775360
      in: path
      name: HMACAuthId
      required: true
      schema:
        type: string
    ConsumerIdForNestedEntities:
      description: Consumer ID for nested entities
      example: ''
      in: path
      name: ConsumerIdForNestedEntities
      required: true
      schema:
        type: string
      x-speakeasy-name-override: consumer_id
    HMACAuthId:
      description: ID of the HMAC-auth credential to lookup
      example: 70e7b00b-72f2-471b-a5ce-9c4171775360
      in: path
      name: HMACAuthId
      required: true
      schema:
        type: string
      x-speakeasy-match: id
    PaginationTagsFilter:
      allowEmptyValue: true
      description: A list of tags to filter the list of resources on. Multiple tags can be concatenated using ',' to mean AND or using '/' to mean OR.
      example: tag1,tag2
      in: query
      name: tags
      schema:
        type: string
  responses:
    HTTP401Error:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GatewayUnauthorizedError'
  securitySchemes:
    adminToken:
      in: header
      name: Kong-Admin-Token
      type: apiKey
externalDocs:
  description: Documentation for Kong Gateway and its APIs
  url: https://developer.konghq.com
